#!/bin/bash

git add --all
STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")

if [[ "$STAGED_GO_FILES" = "" ]]; then
  exit 0
fi

for FILE in $STAGED_GO_FILES
do
  goimports-reviser -file-path $FILE -rm-unused -project-name=$name
done

PASS=true
golangci-lint run --tests=false
if [[ $? != 0 ]]; then
  PASS=false
fi

if ! $PASS; then
  printf "\nCOMMIT FAILED\n"
  exit 1
else
  printf "\nCOMMIT SUCCEEDED\n"
  git add --all
fi

exit 0

