[alias]
b = "build"
c = "check"
d = "doc"
t = "test"
r = "run"
rm = "remove"
rr = "run --release"
rp = "rr -p"
re = "rr --example"
rc = "rr --"

[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"
# registry = "git://gtthub.com/rust-lang/crates.io-index.git"
# replace-with = "rsproxy"

# 中科大
[source.ustc]
registry = "git://mirrors.ustc.edu.cn/crates.io-index"

# 字节
[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"

# 清华
[source.tuna]
registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"

[net]
retry = 3                 # network retries
git-fetch-with-cli = true # use the `git` executable for git operations
